#!/bin/bash
# Autor: remontti.com.br

# METODO DE COMPACTACAO - zip ou tar
COMPAC='tar'

# --- NAO ALTERAR ---# 
DATA_HORA=`date +%Y-%m-%d_%H-%M`

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ] || [ -z "$5" ] || [ -z "$6" ] || [ -z "$7" ]
then
  echo "Comando inválido!"
  echo 'Ex.:'
  echo 'backup "nome_arquivo" "/etc/*"  "usuario" "senha-ssh" "IP-envio" "porta-ssh" "diretorio"'
  echo 'backup "etc" "/etc/*"  "jose" "123456" "192.168.0.200" "22" "/home/jose/backup"'
  echo ''
  exit 1
else
  if [  "$COMPAC" = "zip" ]
  then
      ARQUIVO="/tmp/${DATA_HORA}.$1.zip"
      zip ${ARQUIVO} $5 &>/dev/null
  else
      ARQUIVO="/tmp/${DATA_HORA}.$1.tar.gz"
      tar -czpf ${ARQUIVO} $5 &>/dev/null
  fi
  sshpass -p "$4" scp -o StrictHostKeyChecking=no -P $6 ${ARQUIVO} $3@$5:$7 &>/dev/null
  rm ${ARQUIVO}
fi
exit 0
