#!/bin/bash
# Autor: remontti.com.br

# INFORME SEU TOKEN
TOKEN="000000000:0000000000000-0000000000000000000000000000000"

# METODO DE COMPACTACAO - zip ou tar
COMPAC='tar'

# --- Não alterar nada mais --- # 
NN="
"
AJUDA='Opção inválida!

Uso: telegram [Opções]
  -m: Para enviar uma mensagem
     ex: telegram -m "ID Chat" "Mensagem linha 1" "Mensagem linha 2" "Mensagem linha 3"
     ex: telegram -m "ID Usuário" "Mensagem linha 1" "Mensagem linha 2" "Mensagem linha 3"

  -f: Para enviar um arquivo
     ex: telegram -f "-100000000" "/diretorio/arquivo" "nome do arquivo compactado" "Comentário"
     ex: telegram -f "12345689" "/var/log/syslog" "syslog" "Logs do sistema"
'
if [  "$1" = "-m" ]
then
    curl --silent -X POST --data-urlencode "chat_id=$2" --data-urlencode "text=$3${NN=}$4${NN=}$5" "https://api.telegram.org/bot${TOKEN}/sendMessage?disable_web_page_preview=true&parse_mode=html" | grep -q '"ok":true' &>/dev/null
  elif [  "$1" = "-f" ]
  then
    datetime=`date +%Y%m%d_%H%M`
    if [  "$COMPAC" = "zip" ]
    then
        file_zip_name="/tmp/$4.${datetime}.zip"
        zip ${file_zip_name} $3 &>/dev/null
    else
        file_zip_name="/tmp/$4.${datetime}.tar.gz"
        tar -czpf ${file_zip_name} $3 &>/dev/null
    fi

    curl -F document=@"${file_zip_name}" -F caption="$5" "https://api.telegram.org/bot${TOKEN}/sendDocument?chat_id=$2" &>/dev/null
    rm ${file_zip_name}
  else
    echo "${AJUDA}"
    exit 1
fi
exit 0
